@ECHO OFF
REM *****CREATED BY GUOLIN
REM *****2013-6-7 10:55:00
REM *****HirisunKey.keystore
SET KEYSTORE_PATH=HirisunKey.keystore
SET KEYSTORE_NAME=HirisunKey.keystore
SET KEYSTORE_ALIAS=HirisunKey
SET KEYSTORE_STOREPASS=hirisun
SET KEYSTORE_KEYPASS=hirisun

SET TEMP_PREFIX=TEMP_
SET TEMP_RESIGNER=RESIGNER_

FOR %%I IN (com.hirisun*.jar) DO (
   ECHO Resigner %%I
   
   ECHO JARSIGNER %%I
   REM *****JARSIGNER %%I
   JARSIGNER -KEYSTORE %KEYSTORE_PATH% -STOREPASS %KEYSTORE_STOREPASS% %%I %KEYSTORE_ALIAS% -KEYPASS %KEYSTORE_KEYPASS%
)
PAUSE
@ECHO ON